"""
Release script for iprescribeexercise.com.

Static site, FTP-hosted, no server logic -- so "scheduling" a post means: don't put
its file on the live host, and don't link to it from anywhere, until its post_date
arrives (or a page's page_date, though in practice all 6 pages share the same
page_date -- the site's launch date -- so they all come due together).

Unlike ecolibriumsolar's publish.py (which post-processes the complete site's HTML
with regex to strip not-due content), this site's build_site.py was written to
accept an `as_of` filter directly: it reads only the posts/pages that are due as of
that moment and renders every surface (homepage, blog index, category listings,
individual articles, sitemap.xml) from that filtered dataset alone. That means a due
post's page is generated by the exact same code path whether it's reached through
the complete review build or this pruned one -- nothing to keep in sync by hand.

Usage:
    python publish.py                            # report only, no writes
    python publish.py --build                     # write _deploy/ locally
    python publish.py --build --upload            # also FTP _deploy/ to the live host
    python publish.py --build --upload --commit   # also flip post_status future -> published
    python publish.py --as-of 2026-10-01           # pretend "now" is this date (testing)

--upload and --commit touch the live site / source CSV and are not run automatically.
"""

import argparse
import csv
import ftplib
import re
import sys
from datetime import datetime
from pathlib import Path

SITE_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SITE_DIR))
from build_site import build, is_due, parse_date, read_rows, slugify, POSTS_CSV, PAGES_CSV  # noqa: E402

PORTFOLIO_DIR = POSTS_CSV.parent
HOSTING_CSV = PORTFOLIO_DIR.parent / "hosting_accounts.csv"
DEPLOY_DIR = SITE_DIR / "_deploy"
DOMAIN = "iprescribeexercise.com"


def load_hosting_row():
    with open(HOSTING_CSV, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row["Domain"] == DOMAIN:
                return row
    raise SystemExit(
        f"No hosting_accounts.csv row found for {DOMAIN} -- run hosting_info_transfer "
        "once a hosting welcome email exists for this domain, then retry --upload."
    )


def upload(remote_dir="public_html"):
    host_row = load_hosting_row()
    ftp = ftplib.FTP(host_row["FTP Hostname"])
    ftp.login(host_row["Username"], host_row["Password"])
    if remote_dir != "/":
        ftp.cwd(remote_dir)

    def upload_dir(local_dir, remote_path):
        for entry in sorted(local_dir.iterdir()):
            target = f"{remote_path}/{entry.name}" if remote_path else entry.name
            if entry.is_dir():
                try:
                    ftp.mkd(target)
                except ftplib.error_perm:
                    pass  # already exists
                upload_dir(entry, target)
            else:
                with open(entry, "rb") as f:
                    ftp.storbinary(f"STOR {target}", f)
                print(f"  UPLOADED  {target}")

    upload_dir(DEPLOY_DIR, "")
    ftp.quit()


def commit_status(newly_due_slugs):
    if not newly_due_slugs:
        return
    with open(POSTS_CSV, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames
        rows = list(reader)
    changed = 0
    for row in rows:
        if slugify(row["post_title"]) in newly_due_slugs and row["post_status"] != "published":
            row["post_status"] = "published"
            changed += 1
    with open(POSTS_CSV, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, quoting=csv.QUOTE_ALL, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)
    print(f"Marked {changed} post(s) as published in {POSTS_CSV.name}")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--as-of", help="Pretend 'now' is this date (YYYY-MM-DD), for testing.")
    parser.add_argument("--build", action="store_true", help="Write the _deploy/ folder locally.")
    parser.add_argument("--upload", action="store_true", help="FTP _deploy/ contents to the live host.")
    parser.add_argument("--remote-dir", default="public_html", help="Remote FTP directory to upload into (default: public_html, the account's document root).")
    parser.add_argument("--commit", action="store_true", help="Flip post_status future->published for posts released this run.")
    args = parser.parse_args()

    as_of = datetime.strptime(args.as_of, "%Y-%m-%d") if args.as_of else datetime.now()

    posts = read_rows(POSTS_CSV)
    pages = read_rows(PAGES_CSV)

    print(f"As of {as_of:%Y-%m-%d %H:%M}:")
    for p in sorted(posts, key=lambda r: parse_date(r["post_date"])):
        state = "DUE" if is_due(p.get("post_status", ""), p.get("post_date", ""), as_of) else "not due"
        print(f"  [{state:8}] {p['post_title']}  ({p.get('post_status','')}, {p.get('post_date','')})")
    for p in sorted(pages, key=lambda r: parse_date(r["page_date"])):
        state = "DUE" if is_due(p.get("page_status", ""), p.get("page_date", ""), as_of) else "not due"
        print(f"  [{state:8}] {p['page_title']}  ({p.get('page_status','')}, {p.get('page_date','')}) [page]")

    if not args.build and not args.upload:
        print("\n(report only -- pass --build to write _deploy/, --upload to push it live)")
        return

    due_before = {
        slugify(p["post_title"])
        for p in posts
        if p.get("post_status", "") != "published"
        and is_due(p.get("post_status", ""), p.get("post_date", ""), as_of)
    }

    build(output_dir=DEPLOY_DIR, as_of=as_of)
    print(f"\nBuilt _deploy/ for as-of {as_of:%Y-%m-%d}.")

    if args.upload:
        print(f"\nUploading _deploy/ to {DOMAIN} ...")
        upload(remote_dir=args.remote_dir)
        print("Upload complete.")

    if args.commit:
        if not args.upload:
            print("\n--commit without --upload: updating post_status without anything actually being live. Skipping.", file=sys.stderr)
        else:
            commit_status(due_before)


if __name__ == "__main__":
    main()
